name: build-install-test-snap-lxc

on:
  workflow_call:
    inputs:
      lxc-image:
        required: true
        type: string
      snapcraft-channel:
        required: false
        type: string
        default: "latest/stable"
      snap-name:
        required: true
        type: string
      branch-name:
        required: true
        type: string
      snapcraft-args:
        required: false
        type: string
      snap-install-args:
        required: false
        type: string
      enable-experimental-extensions-env:
        required: false
        type: boolean
      test-script:
        description: "Custom script to run some custom snap testing"
        required: false
        type: string

jobs:
  build-install-test-snap:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - name: Setup LXD
      uses: canonical/setup-lxd@v0.1.1
      with:
        channel: latest/stable
    - name: Launch container
      run: |
        lxc launch '${{ inputs.lxc-image }}' lxc-container
    - uses: actions/checkout@v4
      with:
        ref: '${{ inputs.branch-name }}'
    - uses: snapcore/action-build@v1
      env:
        SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS : '${{ inputs.enable-experimental-extensions-env }}'
      with:
        snapcraft-channel: '${{ inputs.snapcraft-channel }}'
        snapcraft-args: '${{ inputs.snapcraft-args }}'
      id: build-snap
    - name: Push snap to lxc container
      run: |
        lxc file push ${{ steps.build-snap.outputs.snap }} lxc-container/home/ubuntu/
    # Make sure the snap is installable
    - name: Install snap with flags
      if: inputs.snap-install-args != ''
      run: |
        lxc exec lxc-container -- sudo snap install /home/ubuntu/${{ steps.build-snap.outputs.snap }} '${{ inputs.snap-install-args }}'
    - name: Install snap without flags
      if: inputs.snap-install-args == ''
      run: |
        lxc exec lxc-container -- sudo snap install /home/ubuntu/${{ steps.build-snap.outputs.snap }}
  
    - name: Run custom test script
      if: inputs.test-script != ''
      shell: bash
      run: |
        cat > test-script.sh << 'EOF'
          ${{ inputs.test-script }}
        EOF
        lxc file push test-script.sh lxc-container/home/ubuntu/
        lxc exec lxc-container -- bash /home/ubuntu/test-script.sh
    # Do some default testing with the snap
    - name: Test info snap
      if: inputs.test-script == ''
      run: |
        lxc exec lxc-container -- snap info ${{ inputs.snap-name }}
    # Get branch name without forbidden character
    - name: Branch name
      id: branch-name
      run: |
        echo "BRANCH_NAME=$(echo ${{ inputs.branch-name }} | sed "s|\/|\-|")" >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.snap-name }}-${{ steps.branch-name.outputs.BRANCH_NAME }}
        path: ${{ steps.build-snap.outputs.snap }}
