name: build-install-test-snap

on:
  workflow_call:
    inputs:
      ubuntu-image:
        required: false
        type: string
        default: "ubuntu-latest"
      snapcraft-channel:
        required: false
        type: string
        default: "latest/stable"
      snap-name:
        required: true
        type: string
      branch-name:
        required: true
        type: string
      snapcraft-args:
        required: false
        type: string
      snapcraft-build-path:
        required: false
        type: string
        default: "."
      snap-install-args:
        required: false
        type: string
      enable-experimental-extensions-env:
        required: false
        type: boolean
      test-script:
        description: "Custom script to run some custom snap testing"
        required: false
        type: string

jobs:
  build-install-test-snap:
    runs-on: '${{ inputs.ubuntu-image }}'
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: '${{ inputs.branch-name }}'
    - uses: snapcore/action-build@v1
      env:
        SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS : '${{ inputs.enable-experimental-extensions-env }}'
      with:
        path: ${{ input.snapcraft-build-path }}
        snapcraft-channel: '${{ inputs.snapcraft-channel }}'
        snapcraft-args: '${{ inputs.snapcraft-args }}'
      id: build-snap

    # Make sure the snap is installable
    - name: Install snap with flags
      if: inputs.snap-install-args != ''
      run: |
        sudo snap install ${{ steps.build-snap.outputs.snap }} '${{ inputs.snap-install-args }}'
    - name: Install snap without flags
      if: inputs.snap-install-args == ''
      run: |
        sudo snap install ${{ steps.build-snap.outputs.snap }}
  
    - name: Run custom test script
      if: inputs.test-script != ''
      shell: bash
      run: |
        cat > test-script.sh << 'EOF'
          ${{ inputs.test-script }}
        EOF
        bash test-script.sh
    # Do some default testing with the snap
    - name: Test info snap
      if: inputs.test-script == ''
      run: |
        snap info ${{ inputs.snap-name }}
    # Get branch name without forbidden character
    - name: Branch name
      id: branch-name
      run: |
        echo "BRANCH_NAME=$(echo ${{ inputs.branch-name }} | sed "s|\/|\-|")" >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.snap-name }}-${{ steps.branch-name.outputs.BRANCH_NAME }}
        path: ${{ steps.build-snap.outputs.snap }}
